---
title: "Social Media Research Methods: An introduction using R"
author: "Patricia Rossini, University of Liverpool"
date: "7/10/2019"
output: html_document

knit: (function(input_file, encoding) {
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), 'index.html'))})


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### Course Description & Goals 

Social media is now a ubiquitous part of everyday life. People are routinely using social media to communicate with friends and family, follow the latest news, and to participate in politics. As a consequence, researchers have been increasingly interested in understanding the use, nature and effects of social media in everyday life. The scholarly interest on social media use gives rise to a need to think carefully about ethical considerations and methods for studying these channels, as well as the limitations of this type of research.  
This workshop focuses on social media research methods and overviews a variety of computational methods for collecting and analyzing data from social media platforms. It also discusses the implications and limitations – both technical and ethical – of conducting research on social media. The workshop will cover both the theoretical foundations of social media research and the practical skills for collecting and analyzing data. 

This course is meant for any student with an interest in researching human behavior on and around social media platforms, such as Facebook and Twitter. A computer with RStudio installed is required.

**Course Goals**

- Explore ethical considerations of online research 
- Examine the unique challenges and opportunities of research involving social media use.
- Learn methodological techniques for social media research
- Learn techniques for data collection, cleaning and basic analysis 

**Course Outcomes** 

- Understand the ethical considerations unique to social media research methods 
- Understand the relationship between research questions, methods, and available data
- Articulate strengths and weaknesses of methodological approaches 
- Learn how to collect publicly accessible social media data using R
- Learn techniques to clean, visualize and analyze social media data using R



__Readings - [Dropbox](https://www.dropbox.com/sh/xjzua39yr6ttxgo/AACjRj8xlB4w8UMDYMj16FyKa?dl=0)__

- [AoIR's Ethical Decision-Making and Internet Research](https://aoir.org/reports/ethics2.pdf)
- Batrinca, B., & Treleaven, P. C. (2015). Social media analytics: A survey of techniques, tools and platforms. AI & SOCIETY, 30(1), 89–116. https://doi.org/10.1007/s00146-014-0549-4
- boyd,  danah, & Crawford, K. (2012). CRITICAL QUESTIONS FOR BIG DATA: Provocations for a cultural, technological, and scholarly phenomenon. Information, Communication & Society, 15(5), 662–679. https://doi.org/10.1080/1369118X.2012.678878
- Golder, S. A., & Macy, M. W. (2014). Digital Footprints: Opportunities and Challenges for Online Social Research. Annual Review of Sociology, 40(1), 129–152. https://doi.org/10.1146/annurev-soc-071913-043145
- Kramer, A. D. I., Guillory, J. E., & Hancock, J. T. (2014). Experimental evidence of massive-scale emotional contagion through social networks. Proceedings of the National Academy of Sciences, 111(24), 8788–8790. https://doi.org/10.1073/pnas.1320040111
- Zimmer, M. (2010). “But the data is already public”: On the ethics of research in Facebook. Ethics and Information Technology, 12(4), 313–325. https://doi.org/10.1007/s10676-010-9227-5


__Course Materials__

- Day 1
- Day 2

